Add setup script so that contracts repo is runnable after `yarn install`
curio-research/treaty-contracts pull request #275
Opened 2023-01-23 00:15 UTC by ranmocy

2023-01-23 04:33 UTC, Yijia-Chen approved these changes
lgtm

2023-01-23 04:34 UTC, Yijia-Chen requested changes

2023-01-23 04:34 UTC, Yijia-Chen commented on scripts/setup.sh
> +set -e
rename to `pnm-test-setup.sh`

2023-01-23 19:44 UTC, ranmocy commented on scripts/setup.sh
> +set -e
Done

2023-01-25 18:21 UTC, Yijia-Chen approved these changes

2023-01-25 18:21 UTC, merged